apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aura-vault-blue-hpa
  namespace: aura-vault
  labels:
    app: aura-vault
    slot: blue

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aura-vault-blue

  minReplicas: 2
  maxReplicas: 10

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0

    scaleDown:
      stabilizationWindowSeconds: 300

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70